spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${PROD_DB_PORT}/${DB_NAME}?currentSchema=${DEFAULT_SCHEMA}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  liquibase:
    default-schema: ${DEFAULT_SCHEMA}
    change-log: db/changelog/db.changelog.yaml
    liquibase-schema: ${DEFAULT_SCHEMA}
  rabbitmq:
    port: ${PROD_RABBIT_PORT}
    host: ${PROD_RABBIT_HOST}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA}
clevertec:
  rabbit:
    queue:
      currency: ${RABBIT_CURRENCY_QUEUE}
eureka:
  client:
    service-url:
      defaultZone: http://${PROD_EUREKA_HOST}:${EUREKA_PORT}/eureka/